### ISSUE TITLE
TypeError: rotate_factors() missing 1 required positional argument: 'dtype'

### ISSUE THREAD

**Issue by Sergio-Dobrianskiy** [SungjoonPark/factor_rotation#4]
I'm still trying to run example.py. 
Am I doing something wrong here?

loading the model...
pre-trained word2vec model loaded...
converting word2vec embeddings to np_array
rescaling...
0.041875
-0.040625
start rotating...
starting factor parsimax rotation...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-147628d9b04e> in <module>()
     82     method_name = "parsimax"
     83 
---> 84     main()

<ipython-input-2-147628d9b04e> in main()
     71 
     72     print('start rotating...')
---> 73     mat_L, mat_T = method_dic[method_name](unrotated)
     74     export_numpy_array('{}_axis.npy'.format(method_name), mat_T)
     75     export_numpy_array('{}_rotated.npy'.format(method_name), mat_L)

<ipython-input-2-147628d9b04e> in parsimax(unrotated)
     48 def parsimax(unrotated):
     49     print('starting factor parsimax rotation...')
---> 50     return fr.rotate_factors(unrotated, 'parsimax')
     51 
     52 

TypeError: rotate_factors() missing 1 required positional argument: 'dtype'

**Comment by NoSyu** [comment]
Hello
Sorry for late response since I didn't get any notification of issues in this repos.
I've updated the source code to fix these bugs, and test it on tensorflow 1.4
I also add example of input file, so you can see the format of the input file to run your own experiments.
Yours sincerely
